### PR TITLE
Import only Hashable (..)

### LINKED ISSUE #4: Conflict with `hashable==1.2.5.0`: Ambiguous occurrence for `Hashed' and `unhashed'
Unsure if this is something to be fixed in this package or the [`hashable`](https://github.com/tibbe/hashable) package, but thought it was worth posting at the very least to spread awareness.

```
$ cabal install --constraint 'transformers installed' lambdabot-5.1 djinn
…
Building hashable-extras-0.2.3...
Failed to install hashable-extras-0.2.3
Build log ( /root/.cabal/logs/hashable-extras-0.2.3.log ):
cabal: Entering directory '/tmp/cabal-tmp-10/hashable-extras-0.2.3'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-10/hashable-extras-0.2.3/dist/setup/setup.hs, /tmp/cabal-tmp-10/hashable-extras-0.2.3/dist/setup/Main.o )
Linking /tmp/cabal-tmp-10/hashable-extras-0.2.3/dist/setup/setup ...
Configuring hashable-extras-0.2.3...
Building hashable-extras-0.2.3...
Preprocessing library hashable-extras-0.2.3...
[1 of 1] Compiling Data.Hashable.Extras ( src/Data/Hashable/Extras.hs, dist/build/Data/Hashable/Extras.o )

src/Data/Hashable/Extras.hs:30:19: error:
    Ambiguous occurrence `Hashed'
    It could refer to either `Data.Hashable.Hashed',
                             imported from `Data.Hashable' at src/Data/Hashable/Extras.hs:26:1-20
                             (and originally defined in `hashable-1.2.5.0:Data.Hashable.Class')
                          or `Data.Hashable.Extras.Hashed',
                             defined at src/Data/Hashable/Extras.hs:28:1

src/Data/Hashable/Extras.hs:31:22: error:
    Ambiguous occurrence `unhashed'
    It could refer to either `Data.Hashable.unhashed',
                             imported from `Data.Hashable' at src/Data/Hashable/Extras.hs:26:1-20
                             (and originally defined in `hashable-1.2.5.0:Data.Hashable.Class')
                          or `Data.Hashable.Extras.unhashed',
                             defined at src/Data/Hashable/Extras.hs:28:24
cabal: Leaving directory '/tmp/cabal-tmp-10/hashable-extras-0.2.3'
…
cabal: Error: some packages failed to install:
dice-0.1 depends on hashable-extras-0.2.3 which failed to install.
hashable-extras-0.2.3 failed during the building phase. The exception was:
ExitFailure 1
lambdabot-5.1 depends on hashable-extras-0.2.3 which failed to install.
…
```

----

Adding `--constraint=hashable==1.2.4.0` to the `cabal install` gets around the issue.

### PR DESCRIPTION
**Pull request by phadej**
Fix #4, supersede #3

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This seems reasonable.

Slightly related topic: now that we have `Hashable1` and `Hashable2` in `hashable-1.2.5.0`, what is to become of `hashable-extras`? Should it be deprecated?

**Comment by phadej** [comment]
IMHO it should, though `Hashable1` and `Hashed` in `hashable-extras` are different.

**Comment by RyanGlScott** [comment]
I'm not too worried about `Hashable1` in `hashable-extras` being different, since we've shown with `Data.Functor.Classes` that there's a pretty straightforward way to migrate to the lifted version.

I'm not too familiar with `Hashed`, though. Is there a migration story for that?

**Comment by phadej** [comment]
the `Hashed` are different.

`hashable`

```hs
-- | A hashable value along with the result of the 'hash' function.
data Hashed a = Hashed a {-# UNPACK #-} !Int
  deriving (Typeable)
```

`hashable-extras`:

```hs
data Hashed = Hashed { unhashed :: Int -> Int }
```

and AFAICS the latter is used only in `hashable-extras` to implement `hashWith1` and `hashWith2` .
I have a migration PR for `bound`, and it's easy for `approximate` + other numeric libraries.

**Comment by RyanGlScott** [comment]
Ah! Then if `Hashed` is mostly a `hashable-extras` implementation detail, then I have no qualms about deprecating `hashable-extras` in its entirety.

**Comment by RyanGlScott** [comment]
And `hashable-extras` has now been [deprecated](http://hackage.haskell.org/package/hashable-extras-0.2.3) in favor of `hashable`.

**Pull request closed without merging**
